----Cars numeric fields
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('3af1d8bd-750b-4eec-821b-5c6ee26649a7', '36e2c837-320a-4ac0-9aa5-e37d0be1889f', 'Mileage',  'Yurgan masofasi', 'Пробег','Vehicle mileage in kilometers', 'Kilometrdagi transport vositasi yurishi', 'Пробег автомобиля в километрах');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('8b7da8fc-68c8-4ae4-8c6a-710db5c487f3', '36e2c837-320a-4ac0-9aa5-e37d0be1889f', 'Year', 'Yil', 'Год','Manufacturing year', 'Ishlab chiqarilgan yil', 'Год выпуска');


----Motorcycles numeric fields
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('5142f841-9295-4c93-81d5-5aad1b82bc2f', 'c0011135-e8ff-4c1e-aab5-6c6a47451ab4', 'Mileage',  'Yurgan masofasi', 'Пробег','Vehicle mileage in kilometers', 'Kilometrdagi transport vositasi yurishi', 'Пробег автомобиля в километрах');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('0a3ea082-f70a-4800-b9d9-fc4c0b46e226', 'c0011135-e8ff-4c1e-aab5-6c6a47451ab4', 'Year', 'Yil', 'Год','Manufacturing year', 'Ishlab chiqarilgan yil', 'Год выпуска');


----Commercial Vehicle numeric fields
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('e32f5568-e03d-459b-be00-1011cd759e95', '071bb3ee-850e-463d-a140-1ea2f8b0e4fa', 'Mileage',  'Yurgan masofasi', 'Пробег','Vehicle mileage in kilometers', 'Kilometrdagi transport vositasi yurishi', 'Пробег автомобиля в километрах');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('6d844ba5-ca4a-4407-a46c-f23620b9a59f', '071bb3ee-850e-463d-a140-1ea2f8b0e4fa', 'Year', 'Yil', 'Год','Manufacturing year', 'Ishlab chiqarilgan yil', 'Год выпуска');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('097f2cae-e861-47df-aa90-dd0ae66b384c', '071bb3ee-850e-463d-a140-1ea2f8b0e4fa', 'Cargo Capacity', 'Yuk sig‘imi', 'Грузоподъемность',  'Maximum weight of cargo a vehicle can carry', 'Transport vositasi tashishi mumkin bo‘lgan maksimal yuk vazni', 'Максимальная грузоподъемность транспортного средства');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('2da217d7-eed7-4a3d-8870-be54dc099da1', '071bb3ee-850e-463d-a140-1ea2f8b0e4fa', 'GVWR', 'GVWR', 'Полная масса ТС',  'Gross Vehicle Weight Rating, including cargo and passengers', 'Transport vositasining yuk va yo‘lovchilar bilan maksimal og‘irligi', 'Полная масса ТС, включая груз и пассажиров');


----Watercraft numeric fields
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('23d2f9e7-c095-46ff-9d12-eae5daf4667d', '8b9698c6-3b77-47cf-8ad1-3c5845e11797', 'Mileage',  'Yurgan masofasi', 'Пробег','Vehicle mileage in kilometers', 'Kilometrdagi transport vositasi yurishi', 'Пробег автомобиля в километрах');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('feb2dbd4-39d5-4562-ae0c-031a6638b9f7', '8b9698c6-3b77-47cf-8ad1-3c5845e11797', 'Year', 'Yil', 'Год','Manufacturing year', 'Ishlab chiqarilgan yil', 'Год выпуска');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('d5a6c4b7-3e9d-4f6a-8c2b-7e3f1a5d9b8e', '8b9698c6-3b77-47cf-8ad1-3c5845e11797', 'Capacity', 'Sig‘im', 'Вместимость','Maximum weight or number of passengers a watercraft can carry', 'Suv transport vositasining tashishi mumkin bo‘lgan maksimal yuk yoki yo‘lovchilar soni', 'Максимальная вместимость или грузоподъемность водного транспорта');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('c8d4a6b7-9e3f-4f2b-8c1d-5a7e3b6c2f9a', '8b9698c6-3b77-47cf-8ad1-3c5845e11797', 'Length', 'Uzunligi', 'Длина','Total length of the watercraft in meters', 'Suv transport vositasining umumiy uzunligi metrda', 'Общая длина водного транспорта в метрах');



--Special Vehicle numeric fields
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('2121528a-c86d-4394-8076-6dd8e05652a4', '501174fa-8f50-42f7-b2ca-3046c3dc9ae3', 'Mileage',  'Yurgan masofasi', 'Пробег','Vehicle mileage in kilometers', 'Kilometrdagi transport vositasi yurishi', 'Пробег автомобиля в километрах');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('e4e9de1c-ed2d-435c-ae9c-bb1a8a15d175', '501174fa-8f50-42f7-b2ca-3046c3dc9ae3', 'Year', 'Yil', 'Год','Manufacturing year', 'Ishlab chiqarilgan yil', 'Год выпуска');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('a1b2c3d4-e5f6-4789-abcd-1234567890ef', '501174fa-8f50-42f7-b2ca-3046c3dc9ae3', 'Maximum Speed', 'Maksimal tezlik', 'Максимальная скорость','Highest speed the special vehicle can reach in km/h', 'Maxsus transport vositasining maksimal tezligi (km/soat)', 'Максимальная скорость специального транспортного средства (км/ч)');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('b2c3d4e5-f6a7-4890-bcde-2345678901df', '501174fa-8f50-42f7-b2ca-3046c3dc9ae3', 'Weight', 'Og‘irligi', 'Вес','Total weight of the special vehicle in kilograms', 'Maxsus transport vositasining umumiy og‘irligi kilogrammda', 'Общий вес специального транспортного средства в килограммах');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('c3d4e5f6-a7b8-4901-cdef-3456789012af', '501174fa-8f50-42f7-b2ca-3046c3dc9ae3', 'Capacity', 'Sig‘im', 'Вместимость','Maximum load or number of passengers the vehicle can carry', 'Maxsus transport vositasining tashishi mumkin bo‘lgan maksimal yuk yoki yo‘lovchilar soni', 'Максимальная вместимость или грузоподъемность специального транспорта');



----Agricultural & Construction Vehicles numeric fields
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('81adce74-0516-4202-adf7-28c10906dfde', 'ed82f3b9-93af-4574-8039-35f73f49ed10', 'Mileage',  'Yurgan masofasi', 'Пробег','Vehicle mileage in kilometers', 'Kilometrdagi transport vositasi yurishi', 'Пробег автомобиля в километрах');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('fe3a211a-9d14-432a-a195-85c0c35cb020', 'ed82f3b9-93af-4574-8039-35f73f49ed10', 'Year', 'Yil', 'Год','Manufacturing year', 'Ishlab chiqarilgan yil', 'Год выпуска');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('c7c3c6a8-7390-45ec-8c4a-78a5a1b26770', 'ed82f3b9-93af-4574-8039-35f73f49ed10', 'Weight', 'Og‘irligi', 'Вес','Total weight of the agricultural or construction vehicle in kilograms', 'Agrar yoki qurilish transport vositasining umumiy og‘irligi kilogrammda','Общий вес сельскохозяйственного или строительного транспорта в килограммах');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('955a2488-d1c7-453b-ac79-dfc01f9e0a0f', 'ed82f3b9-93af-4574-8039-35f73f49ed10', 'Engine Power', 'Dvigatel quvvati', 'Мощность двигателя',  'Engine power of the vehicle in horsepower (HP) or kilowatts (kW)','Transport vositasining dvigatel quvvati ot kuchida (HP) yoki kilovattlarda (kW)',   'Мощность двигателя транспортного средства в лошадиных силах (HP) или киловаттах (kW)');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('b49e0b18-8f67-4daa-b457-13a5c0d9775a', 'ed82f3b9-93af-4574-8039-35f73f49ed10', 'Max Load Capacity', 'Maksimal yuk sig‘imi', 'Максимальная грузоподъемность','Maximum load capacity the vehicle can carry in kilograms',  'Transport vositasining maksimal yuk tashish sig‘imi kilogrammda', 'Максимальная грузоподъемность транспортного средства в килограммах');


----Electric Vehicles numeric fields
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('487a1cc1-22a6-42ea-af59-659e5e655bd9', '30ed6de6-3a89-4f57-8166-d9f6a29fd81b', 'Mileage',  'Yurgan masofasi', 'Пробег','Vehicle mileage in kilometers', 'Kilometrdagi transport vositasi yurishi', 'Пробег автомобиля в километрах');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('e57af8f8-21ab-44f3-8b1d-976d6a13de1c', '30ed6de6-3a89-4f57-8166-d9f6a29fd81b', 'Year', 'Yil', 'Год','Manufacturing year', 'Ishlab chiqarilgan yil', 'Год выпуска');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('891a55df-240d-4739-a8a7-d0a24d5eb3f3', '30ed6de6-3a89-4f57-8166-d9f6a29fd81b', 'Maximum Speed', 'Maksimal tezlik', 'Максимальная скорость',  'Maximum speed the electric vehicle can reach in kilometers per hour (km/h)', 'Elektr transport vositasining maksimal tezligi km/soatda','Максимальная скорость электрического транспортного средства в км/ч');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('bc892ba0-7171-4a5d-90bb-caf6bbfb936b', '30ed6de6-3a89-4f57-8166-d9f6a29fd81b', 'Battery Capacity', 'Batareya sig‘imi', 'Ёмкость аккумулятора','Battery capacity of the electric vehicle in kilowatt-hours (kWh)','Elektr transport vositasining batareya sig‘imi kilovatt-soat (kWh) da', 'Ёмкость аккумулятора электрического транспортного средства в киловатт-часах (кВт·ч)');

