----Cars numeric fields
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('3af1d8bd-750b-4eec-821b-5c6ee26649a7', '36e2c837-320a-4ac0-9aa5-e37d0be1889f', 'Mileage',  'Yurgan masofasi', 'Пробег','Vehicle mileage in kilometers', 'Kilometrdagi transport vositasi yurishi', 'Пробег автомобиля в километрах');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('8b7da8fc-68c8-4ae4-8c6a-710db5c487f3', '36e2c837-320a-4ac0-9aa5-e37d0be1889f', 'Year', 'Yil', 'Год','Manufacturing year', 'Ishlab chiqarilgan yil', 'Год выпуска');


----Motorcycles numeric fields
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('5142f841-9295-4c93-81d5-5aad1b82bc2f', 'c0011135-e8ff-4c1e-aab5-6c6a47451ab4', 'Mileage',  'Yurgan masofasi', 'Пробег','Vehicle mileage in kilometers', 'Kilometrdagi transport vositasi yurishi', 'Пробег автомобиля в километрах');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('0a3ea082-f70a-4800-b9d9-fc4c0b46e226', 'c0011135-e8ff-4c1e-aab5-6c6a47451ab4', 'Year', 'Yil', 'Год','Manufacturing year', 'Ishlab chiqarilgan yil', 'Год выпуска');

------Commercial Vehicle numeric fields
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('e32f5568-e03d-459b-be00-1011cd759e95', '071bb3ee-850e-463d-a140-1ea2f8b0e4fa', 'Mileage',  'Yurgan masofasi', 'Пробег','Vehicle mileage in kilometers', 'Kilometrdagi transport vositasi yurishi', 'Пробег автомобиля в километрах');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('6d844ba5-ca4a-4407-a46c-f23620b9a59f', '071bb3ee-850e-463d-a140-1ea2f8b0e4fa', 'Year', 'Yil', 'Год','Manufacturing year', 'Ishlab chiqarilgan yil', 'Год выпуска');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('097f2cae-e861-47df-aa90-dd0ae66b384c', '071bb3ee-850e-463d-a140-1ea2f8b0e4fa', 'Cargo Capacity', 'Yuk sig‘imi', 'Грузоподъемность',  'Maximum weight of cargo a vehicle can carry', 'Transport vositasi tashishi mumkin bo‘lgan maksimal yuk vazni', 'Максимальная грузоподъемность транспортного средства');
INSERT INTO numeric_fields (field_id, category_id, field_name, field_name_uz, field_name_ru, description, description_uz, description_ru) VALUES ('2da217d7-eed7-4a3d-8870-be54dc099da1', '071bb3ee-850e-463d-a140-1ea2f8b0e4fa', 'GVWR', 'GVWR', 'Полная масса ТС',  'Gross Vehicle Weight Rating, including cargo and passengers', 'Transport vositasining yuk va yo‘lovchilar bilan maksimal og‘irligi', 'Полная масса ТС, включая груз и пассажиров');

