spring:
  application:
    name: ListIn
  datasource:
    url: jdbc:postgresql://localhost:5432/list_in
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1036878431200-p23es5g8p7g4qa70uel9h4uddjnmbr7o.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code

          facebook:
            client-id: YOUR_FACEBOOK_CLIENT_ID
            client-secret: YOUR_FACEBOOK_CLIENT_SECRET
            scope: public_profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"
            client-authentication-method: post
            authorization-grant-type: authorization_code

  mail:
    host: smtp.gmail.com
    port: 587
    username: listinofficialservice@gmail.com
    password: ghnoklzxuiolmkwx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8000
  error:
    path: error.jsp

application:
  security:
    jwt:
      secret-key: 48656c6c6f2c2068656c6c6f206d79206e616d65206973204967726973303034
      expiration: 31536000000 # 365 days | 86400000 # 1 day  | 60000 1 minute (for testing)
      refresh-token:
        expiration: 31536000000 # 365 days| 604800000 # 7 days

cloud:
  aws:
    credentials:
      access-key: AKIA47CR3SCNNPWHF4MY
      secret-key: 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
    s3:
      bucket:
        bucket-list-in
aws:
  s3:
    bucket:
      link:
        bucket-list-in.s3.eu-central-1.amazonaws.com
