--Smartphones attributes
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('bd4dbd51-8e3a-4725-93cd-61179b328245', 'string', 'Select Brand', 'Select Model', 'oneSelectable', 'oneSelectable', 'Brand', 'Model', 'oneSelectable', 'multiSelectable', 'Smartphone Brand', 'Smartfon Brendi', 'Brendni tanlang', 'Modelni tanlang', 'Brendi', 'Model', 'Бренд смартфона', 'Выберите бренд', 'Выберите модель', 'Бренд', 'Модель');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('677d0449-8b79-43ca-b7ce-7d347ad4c685', 'string', 'Select Storage', 'null', 'oneSelectable', 'null', 'Storage', 'null', 'multiSelectable', 'null', 'Smartphone Storage', 'Smartfon xotirasini', 'Smartfon xotirasi', 'null', 'Xotirasi', 'null', 'Память смартфона', 'Выберите память', 'null', 'Память', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('e0d20756-42e7-44db-aaf1-73a3dfbd24ea', 'string', 'Select Ram', 'null', 'oneSelectable', 'null', 'Ram', 'null', 'multiSelectable', 'null', 'Smartphone RAM', 'Smartfon RAMi', 'RAMni tanlang', 'null', 'RAM', 'null', 'Оперативная память', 'Выберите RAM', 'null', 'RAM', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('438712ca-30b8-47ce-bd14-b08142f31d24', 'string', 'Select Color', 'null', 'colorSelectable', 'null', 'Color', 'null', 'colorMultiSelectable', 'null', 'Smartphone Color', 'Smartfon Rangi', 'Rangni tanlang', 'null', 'Rang', 'null', 'Цвет смартфона', 'Выберите цвет', 'null', 'Цвет', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('81728a91-0557-4e5f-829c-02fee2ef6c7c', 'string', 'Additional accessories', 'null', 'multiSelectable', 'null', 'Accessories', 'null', 'multiSelectable', 'null', 'Accessories', 'Smartfon Aksessuarlari', 'Qoʻshimcha aksessuarlar', 'null', 'Aksessuarlar', 'null', 'Аксессуары', 'Дополнительные аксессуары', 'null', 'Аксессуары', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('a02367cf-7df0-4010-92ed-15553664c792', 'string', 'Select Model', 'null', 'oneSelectable', 'null', 'Model', 'null', 'multiSelectable', 'null', 'Smartphone Brand Model', 'Smartfon Modeli', 'Modelni tanlang', 'null', 'Model', 'null', 'Модель смартфона', 'Выберите модель', 'null', 'Модель', 'null');

--Laptops attributes
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('6f7fdb2d-1f30-49b7-8c69-83df6269b5c9','string','Select Type','null','oneSelectable','null','Type','null','oneSelectable','null','Laptop Type','Noutbuk turi','Turini tanlang','null','Turi','null','Тип ноутбука','Выберите тип','null','Тип','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('c0a2e2ce-7fb3-4306-944d-b6495ec73227','string','Select Brand','Select Model','oneSelectable','oneSelectable','Brand','Model','oneSelectable','multiSelectable','Laptop Brand','Noutbuk Brendi','Brendni tanlang','Modelni tanlang','Brendi','Modeli','Бренд ноутбука','Выберите бренд','Выберите модель','Бренд','Модель');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('b2635cd6-4100-4eea-9e7f-9d010166d7f2','string','Select Processor Brand','Select Processor','oneSelectable','oneSelectable','Processor Brand','Processor Model','oneSelectable','multiSelectable','Laptop Processor Brands','Noutbuk protsessor brendlari','Protsessor brendini tanlang','Protsessorni tanlang','Protsessor brendi','Protsessor modeli','Бренды процессоров ноутбуков','Выберите бренд процессора','Выберите процессор','Бренд процессора','Процессор');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('5be6a6e1-4499-442c-886a-c439fec6e9a4','string','Select GPU Brand','Select GPU','oneSelectable','oneSelectable','GPU Brand','GPU Model','oneSelectable','multiSelectable','Laptop GPU Brands','Noutbuk GPU brendlari','GPU brendini tanlang','GPU modelini tanlang','GPU brendi','GPU modeli','Бренды GPU ноутбуков','Выберите бренд GPU','Выберите GPU','Бренд GPU','GPU');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('66287880-efbd-4143-9ac5-8017d9f0fa55','string','Select Screen Size','null','oneSelectable','null','Screen Size','null','multiSelectable','null','Laptop Screen Size','Noutbuk ekran o‘lchami','Ekran o‘lchamini tanlang','null','Ekran o‘lchami','null','Размер экрана ноутбука','Выберите размер экрана','null','Размер экрана','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('7e26c4a0-8b45-4739-be81-0f93c4322bac','string','Select Ram','null','oneSelectable','null','Ram','null','multiSelectable','null','Laptop RAM','Noutbuk RAM xotirasi','RAM xotirasini tanlang','null','RAM','null','ОЗУ ноутбука','Выберите объем ОЗУ','null','ОЗУ','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('2b7ceac5-d765-40f2-9282-76832d245726','string','Select SSD','null','oneSelectable','null','SSD','null','multiSelectable','null','Laptop SSD Storage','Noutbuk SSD sig‘imi','SSD sig‘imini tanlang','null','SSD','null','SSD накопитель ноутбука','Выберите SSD накопитель','null','SSD','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('04038f3b-4628-410d-bf43-9ec360f62801','string','Select HDD','null','oneSelectable','null','HDD','null','multiSelectable','null','Laptop HDD Storage','Noutbuk HDD sig‘imi','HDD sig‘imini tanlang','null','HDD','null','HDD накопитель ноутбуков','Выберите HDD накопитель','null','HDD','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('f43b1235-4e23-4011-9bbe-88d820c6892c','string','Select Color','null','colorSelectable','null','Color','null','colorMultiSelectable','null','Laptop Color','Noutbuk rangi','Rangni tanlang','null','Rang','null','Цвет ноутбука','Выберите цвет','null','Цвет','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('e198cc5e-b6ce-45d9-9b45-7c97c561f6d0','string','Select Model','null','oneSelectable','null','Model','null','multiSelectable','null','Laptop Brand Model','Noutbuk modeli','Modelni tanlang','null','Modeli','null','Модель ноутбуков','Выберите модель','null','Модель','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('6fedd9c1-7b8f-4107-9467-fdc941007d73','string','Select Processor Models','null','oneSelectable','null','Processor Models','null','multiSelectable','null','Laptop Processor Brand Models','Noutbuk protsessor modellari','Protsessor modelini tanlang','null','Protsessor modeli','null','Модели процессоров ноутбуков','Выберите модель процессора','null','Модель процессора','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('6a133d41-5f09-49aa-b982-c6d393e8fa48','string','Select GPU Models','null','oneSelectable','null','GPU Models','null','multiSelectable','null','Laptop GPU Brand Models','Noutbuk GPU modellari','GPU modelini tanlang','null','GPU modeli','null','Модели GPU ноутбуков','Выберите модель GPU','null','Модель GPU','null');

--Macbooks attributes
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('f0658257-cfc1-4e10-96ad-0af8fe7360f3','string','Select Model','null','oneSelectable','null','Model','null','oneSelectable','null','Macbook Model','Makbuk modeli','Modelni tanlang','null','Model','null','Модель макбука','Выберите модель','null','Модель','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('a5f79e5f-dc21-4e76-94b9-c7cd6775c00e','string','Select Storage','null','oneSelectable','null','Storage','null','multiSelectable','null','Macbook Storage','Makbuk sig‘imi','Sig‘imni tanlang','null','Sig‘im','null','SSD/Накопитель макбука','Выберите накопитель','null','Накопитель','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('365324d3-1fe1-4d05-ab2f-63fa904339b9','string','Select Ram','null','oneSelectable','null','Ram','null','multiSelectable','null','Macbook RAM','Makbuk RAM xotirasi','RAM xotirasini tanlang','null','RAM','null','ОЗУ макбука','Выберите объем ОЗУ','null','ОЗУ','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('cc85b860-f078-41a3-a1f6-d2d7c35b3448','string','Select Battery Capacity','oneSelectable','null','null','Battery Capacity','null','multiSelectable','null','Macbook Battery Capacity','Makbuk batareya sig‘imi','Batareya sig‘imini tanlang','null','Batareya sig‘imi','null','Емкость аккумулятора макбук','Выберите емкость батареи','null','Емкость аккумулятора','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('a6612018-a8a3-4e46-bae7-8fd1f588beb8','string','Select Color','null','colorSelectable','null','Color','null','colorMultiSelectable','null','Macbook Color','Makbuk rangi','Rangni tanlang','null','Rang','null','Цвет макбук','Выберите цвет','null','Цвет','null');

--SmartWatches attributes
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('e420017f-3b54-4236-a839-361b489825bd','string','Select Brand','Select Model','oneSelectable','oneSelectable','Brand','Model','oneSelectable','multiSelectable','Smartwatch Brand','Aqlli soatlar brendi','Brendni tanlang','Modelni tanlang','Brendi','Modeli','Бренд смарт часов','Выберите бренд','Выберите модель','Бренд','Модель');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('67e28662-8b28-4dd2-bd63-26df677ed5f4','string','Select Color','null','colorSelectable','null','Color','null','colorMultiSelectable','null','Smartwatch Color','Aqlli soatlar rangi','Rangni tanlang','null','Rang','null','Цвет smart-часов','Выберите цвет','null','Цвет','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('34c2eb5b-7130-450a-9f2c-fee714199a4f','string','Additional accessories','null','multiSelectable','null','Accessories','null','multiSelectable','null','Smartwatch Accessories','Aqlli soat aksessuarlari','Qo‘shimcha aksessuarlar','null','Aksessuarlar','null','Аксессуары для smart-часов','Выберите аксессуары','null','Аксессуары','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('35e83a5a-aff5-4c24-aeab-7f82d48addee','string','Select Model','null','oneSelectable','null','Model','null','multiSelectable','null','Smartwatch Brand Model','Aqlli soat modelini tanlang','Modelni tanlang','null','Modeli','null','Модель смарт-часов','Выберите модель','null','Модель','null');

--Tablet attributes
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('973884b5-63b5-4ad0-9ca6-7de2f8a40ab3','string','Select Brand','Select Model','oneSelectable','oneSelectable','Brand','Model','oneSelectable','multiSelectable','Tablet Brand','Planshet brendi','Brendni tanlang','Modelni tanlang','Brend','Model','Бренд планшета','Выберите бренд','Выберите модель','Бренд','Модель');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('a57f28a9-1e23-42f4-b1d8-63f35c164cd3','string','Select Storage','null','oneSelectable','null','Storage','null','multiSelectable','null','Tablet Storage','Planshet xotirasi','Xotirani tanlang','null','Xotira','null','Память планшета','Выберите память','null','Память','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('da05c6e8-126d-451c-b10a-d2da8ec5eadf','string','Select Screen Size','null','oneSelectable','null','Screen Size','null','multiSelectable','null','Tablet Screen Size','Planshet ekrani o''lchami','Ekran o''lchamini tanlang','null','Ekran o''lchami','null','Размер экрана планшета','Выберите размер экрана','null','Размер экрана','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('c92beee3-b125-4a70-8a74-129e59a43149','string','Select Model','null','oneSelectable','null','Model','null','multiSelectable','null','Tablet Brand Model','Planshet modeli','Modelni tanlang','null','Model','null','Модель планшета','Выберите модель','null','Модель','null');

--PC attributes
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('3d48a0e2-bf51-4d2c-a9fe-121a91aad8bf', 'string', 'Select Type', 'null', 'oneSelectable', 'null', 'Type', 'null', 'oneSelectable', 'null', 'PC Type', 'Kompyuter turi', 'Turini tanlang', 'null', 'Turi', 'null', 'Тип компьютера', 'Выберите тип', 'null', 'Тип', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('1697540a-f8d1-4fd8-bc91-5bdd19697988', 'string', 'Select Brand', 'Select Model', 'oneSelectable', 'oneSelectable', 'Brand', 'Model', 'oneSelectable', 'multiSelectable', 'PC Brand', 'Kompyuter brendi', 'Brendni tanlang', 'Modelni tanlang', 'Brend', 'Model', 'Бренд компьютера', 'Выберите бренд', 'Выберите модель', 'Бренд', 'Модель');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('059fc660-4d24-43c2-8d98-a0848e6ac7b3','string','Select Processor Brand','Select Processor','oneSelectable','oneSelectable','Processor Brand','Processor Model','oneSelectable','multiSelectable','PC Processor Brand','Kompyuter protsessori','Protsessor brendini tanlang','Protsessorni tanlang','Protsessor brendi','Protsessor modeli','Процессор компьютера','Выберите бренд процессора','Выберите процессор','Бренд процессора','Модель процессора');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('dd2769d4-c6a0-40c6-af4b-819d04129c12','string','Select GPU Brand','Select GPU','oneSelectable','oneSelectable','GPU Brand','GPU','oneSelectable','multiSelectable','PC GPU Brands','Kompyuter videokartasi','Videokarta brendini tanlang','Videokartani tanlang','Videokarta brendi','Videokarta','Видеокарта компьютера','Выберите бренд видеокарты','Выберите видеокарту','Бренд видеокарты','Видеокарта');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('cef16c16-812d-4572-b80b-292cbf8d7d0c','string','Select SSD Storage','null','oneSelectable','null','SSD','null','multiSelectable','null','PC SSD Storage','Kompyuter SSD xotirasi','SSD xotirasini tanlang','null','SSD','null','SSD память компьютера','Выберите объем SSD','null','SSD','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('5b50c211-94fc-4db2-b16c-9d40d1801643','string','Select HDD Storage','null','oneSelectable','null','HDD','null','multiSelectable','null','PC HDD Storage','Kompyuter HDD xotirasi','HDD xotirasini tanlang','null','HDD','null','HDD память компьютера','Выберите объем HDD','null','HDD','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('346a79f0-7fa9-45b3-99d5-9df99794baf1','string','Select RAM','null','oneSelectable','null','RAM','null','multiSelectable','null','PC RAM','Kompyuter tezkor xotirasi','Tezkor xotirani tanlang','null','Tezkor xotira','null','Оперативная память компьютера','Выберите объем RAM','null','RAM','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('8511663a-9738-465e-a2d1-9ba8b65e460b','boolean','Includes Monitor','null','oneSelectable','null','Includes Monitor','null','oneSelectable','null','PC Monitor','Monitor mavjudligi','Monitor mavjudligini tanlang','null','Monitor mavjudligi','null','Наличие монитора','Выберите наличие монитора','null','Наличие монитора','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('d90ef61b-85a9-4ce8-bdfd-fde412efea83','string','Additional Accessories','null','multiSelectable','null','Accessories','null','multiSelectable','null','PC Additional Accessories','Qo''shimcha aksessuarlar','Qo''shimcha aksessuarlarni tanlang','null','Aksessuarlar','null','Дополнительные аксессуары','Выберите аксессуары','null','Аксессуары','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('593d8f29-0ea3-4e57-8040-7845f316d103','string','Select Model','null','oneSelectable','null','Model','null','multiSelectable','null','PC Brand Model','Kompyuter modeli','Modelni tanlang','null','Model','null','Модель компьютера','Выберите модель','null','Модель','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('11d34c04-9c62-484e-87d6-12147e1e5d37','string','Select Processor Model','null','oneSelectable','null','Processor Model','null','multiSelectable','null','PC Processor Model','Protsessor modeli','Protsessor modelini tanlang','null','Protsessor modeli','null','Модель процессора','Выберите модель процессора','null','Модель процессора','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('69995af8-1786-475b-abde-efaa1fd9978e','string','Select GPU Model','null','oneSelectable','null','GPU Model','null','multiSelectable','null','PC GPU Model','Videokarta modeli','Videokarta modelini tanlang','null','Videokarta modeli','null','Модель видеокарты','Выберите модель видеокарты','null','Модель видеокарты','null');

--TV attributes
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('9d74a5b4-f7c1-46a9-9860-b25c72c081e5', 'string', 'Select Type', 'null', 'oneSelectable', 'null', 'Type', 'null', 'oneSelectable', 'null', 'TV Type', 'Televizor turi', 'Turini tanlang', 'null', 'Turi', 'null', 'Тип телевизора', 'Выберите тип', 'null', 'Тип', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('868dc3ff-ae14-48e6-ab01-08bb6cbe497b', 'string', 'Select Brand', 'null', 'oneSelectable', 'null', 'Brand', 'null', 'oneSelectable', 'null', 'TV Brand', 'Televizor brendi', 'Brendni tanlang', 'null', 'Brend', 'null', 'Бренд телевизора', 'Выберите бренд', 'null', 'Бренд', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('509df700-a0be-4c47-8e2c-2053401d7ef5', 'string', 'Select Display Resolution', 'null', 'oneSelectable', 'null', 'Resolution', 'null', 'multiSelectable', 'null', 'TV Resolution', 'Televizor ruxsati', 'Ekran ruxsatini tanlang', 'null', 'Ruxsat', 'null', 'Разрешение телевизора', 'Выберите разрешение экрана', 'null', 'Разрешение', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('7b882258-de90-48fa-a5ce-5f5be45fa2ba', 'string', 'Select Screen Size', 'null', 'oneSelectable', 'null', 'Screen Size', 'null', 'multiSelectable', 'null', 'TV diagonal', 'Televizor diagonali', 'Ekran o`lchamini tanlang', 'null', 'Ekran o`lchami', 'null', 'Диагональ телевизора', 'Выберите размер экрана', 'null', 'Размер экрана', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('09ce8b9a-48c2-45a0-b748-6fdbd3cc465e', 'boolean', 'Smart TV', 'null', 'oneSelectable', 'null', 'Smart TV', 'null', 'oneSelectable', 'null', 'TV is Smart', 'Smart televizor', 'Smart TV', 'null', 'Smart TV', 'null', 'Смарт телевизор', 'Смарт ТВ', 'null', 'Смарт ТВ', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('19a9b2e0-bd16-4728-b3ff-878a79019227', 'boolean', 'HDR Support', 'null', 'oneSelectable', 'null', 'HDR Support', 'null', 'oneSelectable', 'null', 'TV has HDR', 'HDR qo`llab-quvvatlash', 'HDR qo`llab-quvvatlash', 'null', 'HDR qo`llab-quvvatlash', 'null', 'Поддержка HDR', 'Поддержка HDR', 'null', 'Поддержка HDR', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('b88bc920-add8-495a-b789-dad1d846d655', 'boolean', 'Wall Mount Compatible', 'null', 'oneSelectable', 'null', 'Wall Mount Compatible', 'null', 'oneSelectable', 'null', 'TV is Wall Mount Compatible', 'Devorga o`rnatish mumkin', 'Devorga o`rnatish mumkinligi', 'null', 'Devorga o`rnatish', 'null', 'Возможность настенного монтажа', 'Возможность настенного монтажа', 'null', 'Настенный монтаж', 'null');

--Gaming Consoles attributes
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('76662cfc-2a41-4a6a-9289-5e2a905ae052', 'string', 'Select Brand', 'Select Model', 'oneSelectable', 'oneSelectable', 'Brand', 'Model', 'oneSelectable', 'multiSelectable', 'Console Brand', 'O`yin konsoli brendi', 'Brendni tanlang', 'Modelni tanlang', 'Brend', 'Model', 'Бренд игровой консоли', 'Выберите бренд', 'Выберите модель', 'Бренд', 'Модель');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('ec5011f4-3dee-4455-8dcf-4eeb57118f30', 'string', 'Select Storage', 'null', 'oneSelectable', 'null', 'Storage', 'null', 'multiSelectable', 'null', 'Console Storage', 'Xotirani', 'Xotirani tanlang', 'null', 'Xotira', 'null', 'Объем памяти', 'Выберите объем памяти', 'null', 'Память', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('d9cb2699-29e1-469c-8f6e-356ef25caa62', 'boolean', 'VR Support', 'null', 'oneSelectable', 'null', 'VR Support', 'null', 'oneSelectable', 'null', 'Console has VR support', 'VR qo`llab-quvvatlash', 'VR qo`llab-quvvatlash', 'null', 'VR qo`llab-quvvatlash', 'null', 'Поддержка VR', 'Поддержка VR', 'null', 'Поддержка VR', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('7425a352-5548-49f8-991d-bf44a25cfbed', 'boolean', 'Game Bundles', 'null', 'oneSelectable', 'null', 'Game Bundles', 'null', 'oneSelectable', 'null', 'Console Game Bundles', 'O`yin to`plamlari', 'O`yin to`plamlari', 'null', 'O`yin to`plamlari', 'null', 'Игровые комплекты', 'Игровые комплекты', 'null', 'Игровые комплекты', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('bbec554b-851e-4af4-9a53-6ac7fab090ea', 'string', 'Controller Type', 'null', 'oneSelectable', 'null', 'Controller Type', 'null', 'multiSelectable', 'null', 'Console Controller Type', 'Boshqaruvchi turi', 'Boshqaruvchi turini tanlang', 'null', 'Boshqaruvchi turi', 'null', 'Тип контроллера', 'Выберите тип контроллера', 'null', 'Тип контроллера', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('be322821-332e-4579-9ae9-1dc04e3e93b8', 'string', 'Select Color', 'null', 'colorSelectable', 'null', 'Color', 'null', 'colorMultiSelectable', 'null', 'Console Color', 'Konsol rangi', 'Rangni tanlang', 'null', 'Rang', 'null', 'Цвет консоли', 'Выберите цвет', 'null', 'Цвет', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('82e816c1-644c-458d-bc53-2ff99284172c', 'string', 'Select Model', 'null', 'oneSelectable', 'null', 'Model', 'null', 'multiSelectable', 'null', 'Console Brand Model', 'Konsol modeli', 'Modelni tanlang', 'null', 'Model', 'null', 'Модель консоли', 'Выберите модель', 'null', 'Модель', 'null');

--Audio Equipment attributes
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('e1ad8d80-ff32-4669-87aa-aef571a538c8', 'string', 'Select Type', 'null', 'oneSelectable', 'null', 'Type', 'null', 'oneSelectable', 'null', 'Audio Equipment Type', 'Audio jihoz turi', 'Turini tanlang', 'null', 'Turi', 'null', 'Тип аудио оборудования', 'Выберите тип', 'null', 'Тип', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('577c04ee-3df2-4792-b9d5-6e6c0fcb29d8', 'string', 'Connectivity Types', 'null', 'multiSelectable', 'null', 'Connectivity Types', 'null', 'multiSelectable', 'null', 'Audio Equipment Connectivity Types', 'Ulanish turlari', 'Ulanish turlarini tanlang', 'null', 'Ulanish turlari', 'null', 'Типы подключения', 'Выберите типы подключения', 'null', 'Типы подключения', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('4f7f1247-c988-4adb-bec4-d293d3816f4c', 'string', 'Select Color', 'null', 'colorSelectable', 'null', 'Color', 'null', 'colorMultiSelectable', 'null', 'Audio Equipment color', 'Audio jihoz rangi', 'Rangni tanlang', 'null', 'Rang', 'null', 'Цвет аудио оборудования', 'Выберите цвет', 'null', 'Цвет', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('76ddb474-1150-4eaf-8b1d-3e5d9dee2e35', 'string', 'Noise Cancellation', 'null', 'oneSelectable', 'null', 'Noise Cancellation', 'null', 'oneSelectable', 'null', 'Audio Equipment Noise Cancellation', 'Shovqinni yo`qotish', 'Shovqinni yo`qotish darajasi', 'null', 'Shovqinni yo`qotish', 'null', 'Шумоподавление', 'Уровень шумоподавления', 'null', 'Шумоподавление', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('78054b5e-3ccf-4028-84e4-3caf5e55052a', 'string', 'Water Resistance', 'null', 'oneSelectable', 'null', 'Water Resistance', 'null', 'oneSelectable', 'null', 'Audio Equipment Water Resistance Standard', 'Suv o`tkazmaslik darajasi', 'Suv o`tkazmaslik darajasini tanlang', 'null', 'Suv o`tkazmaslik', 'null', 'Степень водонепроницаемости', 'Выберите степень водонепроницаемости', 'null', 'Водонепроницаемость', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('0b131921-9b8c-416a-a8ab-51c4b185abf8', 'boolean', 'Microphone', 'null', 'oneSelectable', 'null', 'Microphone', 'null', 'oneSelectable', 'null', 'Audio Equipment has Microphone', 'Mikrofon mavjudligi', 'Mikrofon', 'null', 'Mikrofon', 'null', 'Наличие микрофона', 'Микрофон', 'null', 'Микрофон', 'null');

--Photo and Video attributes
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('a24bcfea-bce5-48a8-8b7a-fcd0cfacf97c', 'string', 'Select Equipment Type', 'null', 'oneSelectable', 'null', 'Type', 'null', 'oneSelectable', 'null', 'Photo/Video Equipment Type', 'Foto/Video jihoz turi', 'Jihoz turini tanlang', 'null', 'Tur', 'null', 'Тип фото/видео оборудования', 'Выберите тип оборудования', 'null', 'Тип', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('4b10e786-7060-4f47-8978-7ed1409816ac', 'string', 'Weight', 'null', 'oneSelectable', 'null', 'Weight', 'null', 'multiSelectable', 'null', 'Photo/Video Equipment Weight', 'Foto/Video jihoz og`irligi', 'Og`irlikni tanlang', 'null', 'Og`irlik', 'null', 'Вес фото/видео оборудования', 'Выберите вес', 'null', 'Вес', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('d4f7f031-88b7-4a4e-aa9b-1e53c68b9b70', 'string', 'Megapixels', 'null', 'oneSelectable', 'null', 'Megapixels', 'null', 'multiSelectable', 'null', 'Camera Megapixels', 'Kamera megapikseli', 'Megapikselni tanlang', 'null', 'Megapiksel', 'null', 'Мегапиксели камеры', 'Выберите мегапиксели', 'null', 'Мегапиксели', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('d2b8185b-0cad-4e19-b6a5-0e1deda15d71', 'string', 'Video Resolution', 'null', 'oneSelectable', 'null', 'Resolution', 'null', 'multiSelectable', 'null', 'Camera Video Resolution', 'Video ruxsati', 'Video ruxsatini tanlang', 'null', 'Ruxsat', 'null', 'Разрешение видео', 'Выберите разрешение видео', 'null', 'Разрешение', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('6deabe92-a76c-4a26-bc43-ae04a9d42c8a', 'string', 'Sensor Type', 'null', 'oneSelectable', 'null', 'Sensor Type', 'null', 'multiSelectable', 'null', 'Photo/Video equipment Sensor Type', 'Sensor turi', 'Sensor turini tanlang', 'null', 'Sensor turi', 'null', 'Тип сенсора', 'Выберите тип сенсора', 'null', 'Тип сенсора', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('ecd6cf34-e80b-40f9-a5ba-f88d8dc70ded', 'string', 'Stabilization', 'null', 'oneSelectable', 'null', 'Stabilization', 'null', 'multiSelectable', 'null', 'Camera Stabilization Type', 'Stabilizatsiya turi', 'Stabilizatsiya turini tanlang', 'null', 'Stabilizatsiya', 'null', 'Тип стабилизации', 'Выберите тип стабилизации', 'null', 'Стабилизация', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('4f46dd1c-ba8e-4e5c-9c51-3e47df87abf1', 'string', 'ISO Range', 'null', 'oneSelectable', 'null', 'ISO Range', 'null', 'multiSelectable', 'null', 'Camera ISO Range', 'ISO diapazoni', 'ISO diapazonini tanlang', 'null', 'ISO diapazoni', 'null', 'Диапазон ISO', 'Выберите диапазон ISO', 'null', 'Диапазон ISO', 'null');

--Home Electronics attributes
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('1fb4b553-a8d8-4563-9352-5a8889c2a13f', 'string', 'Select Type', 'Select Brand', 'oneSelectable', 'oneSelectable', 'Type', 'Brand', 'oneSelectable', 'oneSelectable', 'Home Electronics Type', 'Maishiy texnika turi', 'Turini tanlang', 'Brendni tanlang', 'Tur', 'Brend', 'Тип бытовой техники', 'Выберите тип', 'Выберите бренд', 'Тип', 'Бренд');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('536e35f6-8999-4f3c-a2b2-729560594eb3', 'string', 'Select Brand', 'null', 'oneSelectable', 'null', 'Brand', 'null', 'oneSelectable', 'null', 'Home Electronics Brands', 'Maishiy texnika brendlari', 'Brendni tanlang', 'null', 'Brend', 'null', 'Бренды бытовой техники', 'Выберите бренд', 'null', 'Бренд', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('046fc206-f7f5-4c7d-aabf-5550666b6b99', 'string', 'Select Color', 'null', 'colorSelectable', 'null', 'Color', 'null', 'colorMultiSelectable', 'null', 'Home Electronics Color', 'Maishiy texnika rangi', 'Rangni tanlang', 'null', 'Rang', 'null', 'Цвет бытовой техники', 'Выберите цвет', 'null', 'Цвет', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('a1fa350a-a2a9-420c-a75e-dda7917e317b', 'string', 'Control Type', 'null', 'oneSelectable', 'null', 'Control Type', 'null', 'multiSelectable', 'null', 'Home Electronics Control Type', 'Boshqaruv turi', 'Boshqaruv turini tanlang', 'null', 'Boshqaruv turi', 'null', 'Тип управления', 'Выберите тип управления', 'null', 'Тип управления', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru ) VALUES ('3fc333c3-096d-4762-a60e-e0a2368ec8c8', 'string', 'Warranty Period', 'null', 'oneSelectable', 'null', 'Warranty Period', 'null', 'multiSelectable', 'null', 'Home Electronics Warranty period', 'Kafolat muddati', 'Kafolat muddatini tanlang', 'null', 'Kafolat muddati', 'null', 'Гарантийный срок', 'Выберите гарантийный срок', 'null', 'Гарантийный срок', 'null');


--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


--Cars attributes
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('49405788-6d5a-4736-b30a-59f77e6ed121', 'string', 'Select Brand', 'Select Model', 'oneSelectable', 'oneSelectable', 'Brand', 'Model', 'oneSelectable', 'multiSelectable', 'Cars', 'Avtomobillar', 'Brendni tanlang', 'Modelni tanlang', 'Brand', 'Model', 'Автомобили', 'Выберите бренд', 'Выберите модель', 'Бренд', 'Модель');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('d123105b-3eae-43a7-96e2-2f0f259e691a', 'string', 'Select Model', 'null', 'oneSelectable', 'null', 'Model', 'null', 'multiSelectable', 'null', 'Car brand model', 'Avtomobil modeli', 'Modelni tanlang', 'null', 'Modeli', 'null', 'Модель автомобиля', 'Выберите модель', 'null', 'Модель', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('89fa715a-1094-4f70-96de-dbd016832615', 'string', 'Select Year', 'null', 'oneSelectable', 'null', 'Year', 'null', 'multiSelectable', 'null', 'Year', 'Ishlab chiqarilgan yili', 'Yilini tanlang', 'null', 'Yil', 'null', 'Год выпуска', 'Выберите год', 'null', 'Год', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('92a2afb8-86eb-4650-b384-0b183a2fb915', 'string', 'Select Transmission Type', 'null', 'oneSelectable', 'null', 'Transmission', 'null', 'multiSelectable', 'null', 'Transmission Type', 'Uzatish qutisi turi', 'Uzatish qutisi turini tanlang', 'null', 'Uzatish qutisi', 'null', 'Тип коробки передач', 'Выберите тип коробки передач', 'null', 'Коробка передач', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('ac27bfec-6ac0-4766-8cfe-9918c6f6e291', 'string', 'Select Engine Type', 'null', 'oneSelectable', 'null', 'Engine Type', 'null', 'multiSelectable', 'null', 'Engine Type', 'Motor turi', 'Motor turini tanlang', 'null', 'Motor turi', 'null', 'Тип двигателя', 'Выберите тип двигателя', 'null', 'Тип двигателя', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('7000ea33-e422-490d-972b-e38b1da6b934', 'string', 'Select Engine Size', 'null', 'oneSelectable', 'null', 'Engine Size', 'null', 'multiSelectable', 'null', 'Engine Size', 'Motor xajmi', 'Motor xajmini tanlang', 'null', 'Motor xajmi', 'null', 'Объём двигателя', 'Выберите объём двигателя', 'null', 'Объём двигателя', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('e000082e-632c-4019-a99d-5ed05f74c91c', 'string', 'Select Drive Type', 'null', 'oneSelectable', 'null', 'Drive Type', 'null', 'multiSelectable', 'null', 'Drive Type', 'Boshqaruv turi', 'Boshqaruv turini tanlang', 'null', 'Boshqaruv turi', 'null', 'Тип привода', 'Выберите тип привода', 'null', 'Привод', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('a63f523a-cdfa-42db-b9a3-d4c2d9b2a992', 'string', 'Select Body Color', 'null', 'colorSelectable', 'null', 'Body Color', 'null', 'colorMultiSelectable', 'null', 'Body Color', 'Kuzov rangi', 'Kuzov rangini tanlang', 'null', 'Kuzov rangi', 'null', 'Цвет кузова', 'Выберите цвет кузова', 'null', 'Цвет кузова', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('bcad079c-532e-4474-b9ed-568f34792f2a', 'string', 'Select Interior Color', 'null', 'colorSelectable', 'null', 'Interior Color', 'null', 'colorMultiSelectable', 'null', 'Interior Color', 'Salon rangi', 'Salon rangini tanlang', 'null', 'Salon rangi', 'null', 'Цвет салона', 'Выберите цвет салона', 'null', 'Цвет салона', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('2f01906f-4b83-4d9b-9877-88ce573dadd0', 'string', 'Select Interior Material', 'null', 'oneSelectable', 'null', 'Interior Material', 'null', 'multiSelectable', 'null', 'Interior Material', 'Salon materiali', 'Salon materialini tanlang', 'null', 'Salon materiali', 'null', 'Материал салона', 'Выберите материал салона', 'null', 'Материал салона', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('e819297c-5420-4a1f-b65b-ce04fcf15753', 'string', 'Select Trim Level', 'null', 'oneSelectable', 'null', 'Trim Level', 'null', 'multiSelectable', 'null', 'Trim Level', 'Komplektatsiy', 'Komplektatsiyani tanlang', 'null', 'Komplektatsiy', 'null', 'Комплектация', 'Выберите комплектацию', 'null', 'Комплектация', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('ca37f042-7928-4c4b-9f48-f5d2b0e23313', 'string', 'Select Fuel Type', 'null', 'oneSelectable', 'null', 'Fuel Type', 'null', 'multiSelectable', 'null', 'Fuel Type', 'Yoqilg''i turi', 'Yoqilg''i turini tanlang', 'null', 'Yoqilg''i turi', 'null', 'Тип топлива', 'Выберите тип топлива', 'null', 'Тип топлива', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('bdeb42b2-3af0-468d-8af4-7f76637352b1', 'string', 'Select Number of Doors', 'null', 'oneSelectable', 'null', 'Doors', 'null', 'multiSelectable', 'null', 'Number of Doors', 'Eshiklar soni', 'Eshiklar sonini tanlang', 'null', 'Eshiklar soni', 'null', 'Количество дверей', 'Выберите количество дверей', 'null', 'Двери', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('2647f9fe-2eb5-4413-b4d4-d04843b78f14', 'string', 'Select Mileage Range', 'null', 'oneSelectable', 'null', 'Mileage', 'null', 'multiSelectable', 'null', 'Mileage Range', 'Yurgan masofasi', 'Yurgan masofasini tanlang', 'null', 'Yurgan masofasi', 'null', 'Пробег', 'Выберите пробег', 'null', 'Пробег', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('638db714-0d66-40cc-aad6-cfd5e1f9a4cd', 'string', 'Write Down Description Text', 'null','textFiled', 'null','null', 'null', 'null', 'null', 'Description Text','Tavsif matni','Tavsif matn yozing','null','null','null','Текст описания', 'Напишите текст описание', 'null', 'null', 'null');

--Motorcycles attributes
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('678b36da-10a1-4bf6-acb5-7b44bc6695d4', 'string', 'Select Type', 'null', 'oneSelectable', 'null', 'Type', 'null', 'multiSelectable', 'null', 'Motorcycle Type', 'Mototsikl turi', 'Mototsikl turini tanlang', 'null', 'Turi', 'null', 'Тип мотоцикла', 'Выберите тип мотоцикла', 'null', 'Тип', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('6338cc28-1a5a-4769-bed5-c3fb38f99fbe', 'string', 'Select Brand', 'Select Model', 'oneSelectable', 'oneSelectable', 'Brand', 'Model', 'oneSelectable', 'multiSelectable', 'Motorcycle', 'Mototsikl', 'Brendni tanlang', 'Modelni tanlang', 'Brend', 'Model', 'Мотоцикл', 'Выберите бренд', 'Выберите модель', 'Бренд', 'Модель');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('d123105b-3eae-43a7-96e2-2f0f259e693c', 'string', 'Select Model', 'null','oneSelectable','null','Model','null','multiSelectable','null','Motorcycle Model','Mototsikl modeli' ,'Modelni tanlang','null','Model','null','Модель мотоцикла','Выберите модель','null','Модель','null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('92674969-6a77-41ee-b02e-f3843b098e8d', 'string', 'Select Year', 'null', 'oneSelectable', 'null', 'Year', 'null', 'multiSelectable', 'null', 'Year', 'Ishlab chiqarilgan yili', 'Yilini tanlang', 'null', 'Yil', 'null', 'Год выпуска', 'Выберите год', 'null', 'Год', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('26c839de-3b71-4956-b81f-8485ca332da9', 'string', 'Select Engine Type', 'null', 'oneSelectable', 'null', 'Engine Type', 'null', 'multiSelectable', 'null', 'Engine Type', 'Dvigatel turi', 'Dvigatel turini tanlang', 'null', 'Dvigatel turi', 'null', 'Тип двигателя', 'Выберите тип двигателя', 'null', 'Тип двигателя', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('1d1e8a37-2c64-45f7-a545-8ee3fb16abca', 'string', 'Select Engine Size', 'null', 'oneSelectable', 'null', 'Engine Size', 'null', 'multiSelectable', 'null', 'Engine Size', 'Dvigatel hajmi', 'Dvigatel hajmini tanlang', 'null', 'Dvigatel hajmi', 'null', 'Объём двигателя', 'Выберите объём двигателя', 'null', 'Объём двигателя', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('73c742e1-a1fd-4a58-87a4-29fac9f04cd8', 'string', 'Select Transmission Type', 'null', 'oneSelectable', 'null', 'Transmission', 'null', 'multiSelectable', 'null', 'Transmission Type', 'Uzatish qutisi turi', 'Uzatish qutisi turini tanlang', 'null', 'Uzatish qutisi', 'null', 'Тип коробки передач', 'Выберите тип коробки передач', 'null', 'Коробка передач', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('09e4d3fe-9cfb-4dd6-876d-b4177854d9de', 'string', 'Select Drive Type', 'null', 'oneSelectable', 'null', 'Drive Type', 'null', 'multiSelectable', 'null', 'Drive Type', 'Yuritish turi', 'Yuritish turini tanlang', 'null', 'Yuritish turi', 'null', 'Тип привода', 'Выберите тип привода', 'null', 'Привод', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('2395b514-7eda-4129-9c1a-36bd75290588', 'string', 'Select Body Color', 'null', 'colorSelectable', 'null', 'Body Color', 'null', 'colorMultiSelectable', 'null', 'Body Color', 'Rang', 'Rangni tanlang', 'null', 'Rang', 'null', 'Цвет', 'Выберите цвет', 'null', 'Цвет', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('677102af-0853-4eda-8ee0-982760e0f57b', 'string', 'Select Fuel System', 'null', 'oneSelectable', 'null', 'Fuel System', 'null', 'multiSelectable', 'null', 'Fuel System', 'Yoqilg''i tizimi', 'Yoqilg''i tizimini tanlang', 'null', 'Yoqilg''i tizimi', 'null', 'Топливная система', 'Выберите топливную систему', 'null', 'Топливная система', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('01d43720-8839-4cd2-b9a4-e63ae1b3fb32', 'string', 'Select Cooling System', 'null', 'oneSelectable', 'null', 'Cooling System', 'null', 'multiSelectable', 'null', 'Cooling System', 'Sovutish tizimi', 'Sovutish tizimini tanlang', 'null', 'Sovutish tizimi', 'null', 'Система охлаждения', 'Выберите систему охлаждения', 'null', 'Система охлаждения', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('84dcca47-6875-4fd1-9821-1f4631405d4c', 'string', 'Select Starting System', 'null', 'oneSelectable', 'null', 'Starting System', 'null', 'multiSelectable', 'null', 'Starting System', 'Ishga tushirish tizimi', 'Ishga tushirish tizimini tanlang', 'null', 'Ishga tushirish', 'null', 'Система запуска', 'Выберите систему запуска', 'null', 'Система запуска', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('fdb012ec-6cc0-473c-9c40-512e3accfefa', 'string', 'Select Brake Type', 'null', 'oneSelectable', 'null', 'Brake Type', 'null', 'multiSelectable', 'null', 'Brake Type', 'Tormoz turi', 'Tormoz turini tanlang', 'null', 'Tormoz turi', 'null', 'Тип тормозов', 'Выберите тип тормозов', 'null', 'Тип тормозов', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('0c7da91c-f9a2-450b-9167-b40a8efd779b', 'string', 'Select Number of Cylinders', 'null', 'oneSelectable', 'null', 'Cylinders', 'null', 'multiSelectable', 'null', 'Number of Cylinders', 'Tsilindrlar soni', 'Tsilindrlar sonini tanlang', 'null', 'Tsilindrlar', 'null', 'Количество цилиндров', 'Выберите количество цилиндров', 'null', 'Цилиндры', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('4167ffb5-0ff6-452a-a25d-f215375c51f9', 'string', 'Select Mileage Range', 'null', 'oneSelectable', 'null', 'Mileage', 'null', 'multiSelectable', 'null', 'Mileage Range', 'Yurgan masofasi', 'Yurgan masofasini tanlang', 'null', 'Yurgan masofasi', 'null', 'Пробег', 'Выберите пробег', 'null', 'Пробег', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('2c264ce2-49d3-4db5-b0b2-16a7a6788646', 'string', 'Write Down Description Text', 'null','textFiled', 'null','null', 'null', 'null', 'null', 'Description Text','Tavsif matni','Tavsif matn yozing','null','null','null','Текст описания', 'Напишите текст описание', 'null', 'null', 'null');

--Commercial Vehicles attributes
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('6f58e53d-f94b-47ca-9920-3a71818787f0', 'string', 'Select Type', 'null', 'oneSelectable', 'null', 'Type', 'null', 'multiSelectable', 'null', 'Commercial Vehicle Type', 'Tijorat transport vositasi turi', 'Transport vositasi turini tanlang', 'null', 'Turi', 'null', 'Тип коммерческого транспорта', 'Выберите тип транспорта', 'null', 'Тип', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('4e15c596-ad00-4475-9202-01ac840b964f', 'string', 'Select Brand', 'Select Model', 'oneSelectable', 'oneSelectable', 'Brand', 'Model', 'oneSelectable', 'multiSelectable', 'Commercial Vehicle', 'Tijorat transporti', 'Brendni tanlang', 'Modelni tanlang', 'Brend', 'Model', 'Коммерческий транспорт', 'Выберите бренд', 'Выберите модель', 'Бренд', 'Модель');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('e88fa0a3-92c3-4b15-bd1d-fc8d5f9ef798', 'string', 'Select Model', 'null', 'oneSelectable', 'null', 'Model', 'null', 'multiSelectable', 'null', 'Commercial Vehicle Model', 'Tijorat transport modeli', 'Modelni tanlang', 'null', 'Model', 'null', 'Модель коммерческого транспорта', 'Выберите модель', 'null', 'Модель', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('5063df64-127e-47f3-9d2a-8c1a865b16f6', 'string', 'Select Year', 'null', 'oneSelectable', 'null', 'Year', 'null', 'multiSelectable', 'null', 'Year', 'Ishlab chiqarilgan yili', 'Yilini tanlang', 'null', 'Yil', 'null', 'Год выпуска', 'Выберите год', 'null', 'Год', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('f44c3596-5166-4740-9702-25dfc0191b74', 'string', 'Select Body Type', 'null', 'oneSelectable', 'null', 'Body Type', 'null', 'multiSelectable', 'null', 'Body Type', 'Kuzov turi', 'Kuzov turini tanlang', 'null', 'Kuzov turi', 'null', 'Тип кузова', 'Выберите тип кузова', 'null', 'Тип кузова', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('0a21bf8f-8257-4f72-b5ef-da380505548a', 'string', 'Select Transmission Type', 'null', 'oneSelectable', 'null', 'Transmission', 'null', 'multiSelectable', 'null', 'Transmission Type', 'Uzatish qutisi turi', 'Uzatish qutisi turini tanlang', 'null', 'Uzatish qutisi', 'null', 'Тип коробки передач', 'Выберите тип коробки передач', 'null', 'Коробка передач', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('972af0aa-3dcb-4580-8a28-c041285d1ea3', 'string', 'Select Engine Type', 'null', 'oneSelectable', 'null', 'Engine Type', 'null', 'multiSelectable', 'null', 'Engine Type', 'Dvigatel turi', 'Dvigatel turini tanlang', 'null', 'Dvigatel turi', 'null', 'Тип двигателя', 'Выберите тип двигателя', 'null', 'Тип двигателя', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('e5abf5b5-7b6f-4361-b92e-5aeab82ba9ae', 'string', 'Select Engine Size', 'null', 'oneSelectable', 'null', 'Engine Size', 'null', 'multiSelectable', 'null', 'Engine Size', 'Dvigatel hajmi', 'Dvigatel hajmini tanlang', 'null', 'Dvigatel hajmi', 'null', 'Объём двигателя', 'Выберите объём двигателя', 'null', 'Объём двигателя', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('be3530ce-adf9-4f67-b1a5-119046f2dfce', 'string', 'Select Drive Type', 'null', 'oneSelectable', 'null', 'Drive Type', 'null', 'multiSelectable', 'null', 'Drive Type', 'Yuritish turi', 'Yuritish turini tanlang', 'null', 'Yuritish turi', 'null', 'Тип привода', 'Выберите тип привода', 'null', 'Привод', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('9d5a28da-ef9b-4687-ad2a-2603a2121c94', 'string', 'Select Body Color', 'null', 'colorSelectable', 'null', 'Body Color', 'null', 'colorMultiSelectable', 'null', 'Body Color', 'Kuzov rangi', 'Kuzov rangini tanlang', 'null', 'Rang', 'null', 'Цвет кузова', 'Выберите цвет кузова', 'null', 'Цвет', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('af5e4d19-35e2-44e4-8657-377ef8f7c525', 'string', 'Select Cargo Capacity', 'null', 'oneSelectable', 'null', 'Cargo Capacity', 'null', 'multiSelectable', 'null', 'Cargo Capacity', 'Yuk sig''imi', 'Yuk sig''imini tanlang', 'null', 'Yuk sig''imi', 'null', 'Грузоподъёмность', 'Выберите грузоподъёмность', 'null', 'Грузоподъёмность', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('643be0f2-1d41-440d-b33e-5c19306c6f4d', 'string', 'Select GVWR', 'null', 'oneSelectable', 'null', 'GVWR', 'null', 'multiSelectable', 'null', 'Gross Vehicle Weight Rating', 'Umumiy og''irlik reytingi', 'Umumiy og''irlik reytingini tanlang', 'null', 'Umumiy og''irlik', 'null', 'Полная масса', 'Выберите полную массу', 'null', 'Полная масса', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('9b5d61d3-e566-46fc-9974-f54784212461', 'string', 'Select Number of Axles', 'null', 'oneSelectable', 'null', 'Axles', 'null', 'multiSelectable', 'null', 'Number of Axles', 'O''qlar soni', 'O''qlar sonini tanlang', 'null', 'O''qlar', 'null', 'Количество осей', 'Выберите количество осей', 'null', 'Оси', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('8ed47d56-6fce-44ef-baf4-fa99c316837e', 'string', 'Select Fuel Type', 'null', 'oneSelectable', 'null', 'Fuel Type', 'null', 'multiSelectable', 'null', 'Fuel Type', 'Yoqilg''i turi', 'Yoqilg''i turini tanlang', 'null', 'Yoqilg''i', 'null', 'Тип топлива', 'Выберите тип топлива', 'null', 'Топливо', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('b93f7c35-c4b5-44a1-a26d-df3ec21cf961', 'string', 'Select Cabin Type', 'null', 'oneSelectable', 'null', 'Cabin', 'null', 'multiSelectable', 'null', 'Cabin Type', 'Kabina turi', 'Kabina turini tanlang', 'null', 'Kabina turi', 'null', '', 'Тип каюты', 'Выберите тип каюты', 'Тип каюты', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('90cc9185-c865-4ed2-bf41-ba59e8c6b51c', 'string', 'Select Mileage Range', 'null', 'oneSelectable', 'null', 'Mileage', 'null', 'multiSelectable', 'null', 'Mileage Range', 'Yurgan masofasi', 'Yurgan masofasini tanlang', 'null', 'Yurgan masofasi', 'null', 'Пробег', 'Выберите пробег', 'null', 'Пробег', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('5ad4f4a1-5b5e-4d65-a4a1-20d321bb24e9', 'string', 'Write Down Description Text', 'null','textFiled', 'null','null', 'null', 'null', 'null', 'Description Text','Tavsif matni','Tavsif matn yozing','null','null','null','Текст описания', 'Напишите текст описание', 'null', 'null', 'null');

--Watercraft attributes
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('2430cfc1-841f-45be-be2d-4359909aa4d4', 'string', 'Select Type', 'null', 'oneSelectable', 'null', 'Type', 'null', 'multiSelectable', 'null', 'Watercraft Type', 'Suv transport vositasi turi', 'Suv transport vositasi turini tanlang', 'null', 'Turi', 'null', 'Тип водного транспорта', 'Выберите тип водного транспорта', 'null', 'Тип', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('c8486485-3070-4fe4-a402-336c630209e4', 'string', 'Select Brand', 'Select Model', 'oneSelectable', 'oneSelectable', 'Brand', 'Model', 'oneSelectable', 'multiSelectable', 'Watercraft Brand', 'Suv transporti brendi', 'Brendni tanlang', 'Modelni tanlang', 'Brend', 'Model', 'Бренд водного транспорта', 'Выберите бренд', 'Выберите модель', 'Бренд', 'Модель');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('ab536402-9d7c-438b-b0e7-b1a5897c8d76', 'string', 'Select Model', 'null', 'oneSelectable', 'null', 'Model', 'null', 'multiSelectable', 'null', 'Watercraft Model', 'Suv transport modeli', 'Modelni tanlang', 'null', 'Model', 'null', 'Модель водного транспорта', 'Выберите модель', 'null', 'Модель', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('54f75fdd-f5fa-443d-afd7-1b871dfaa6eb', 'string', 'Select Year', 'null', 'oneSelectable', 'null', 'Year', 'null', 'multiSelectable', 'null', 'Manufacturing Year', 'Ishlab chiqarilgan yili', 'Yilini tanlang', 'null', 'Yil', 'null', 'Год выпуска', 'Выберите год', 'null', 'Год', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('ab509ef0-cbfb-43d6-92c0-62bd76ef545a', 'string', 'Select Hull Type', 'null', 'oneSelectable', 'null', 'Hull Type', 'null', 'multiSelectable', 'null', 'Hull Type', 'Kema korpusi turi', 'Kema korpusi turini tanlang', 'null', 'Korpusi Turi', 'null', 'Тип корпуса', 'Выберите тип корпуса', 'null', 'Тип корпуса', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('9279b7af-65f6-4561-9bfa-d57e41e00f39', 'string', 'Select Transmission Type', 'null', 'oneSelectable', 'null', 'Transmission Type', 'null', 'multiSelectable', 'null', 'Transmission Type', 'Uzatma turi', 'Uzatma turini tanlang', 'null', 'Uzatma turi', 'null', 'Тип трансмиссии', 'Выберите тип трансмиссии', 'null', 'Тип трансмиссии', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('57937787-8f68-4ea7-83db-d1ddda979725', 'string', 'Select Engine Type', 'null', 'oneSelectable', 'null', 'Engine Type', 'null', 'multiSelectable', 'null', 'Engine Type', 'Dvigatel turi', 'Dvigatel turini tanlang', 'null', 'Dvigatel turi', 'null', 'Тип двигателя', 'Выберите тип двигателя', 'null', 'Тип двигателя', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('20d77aa8-e7a5-4323-9ab3-347e5a9a6358', 'string', 'Select Engine Size', 'null', 'oneSelectable', 'null', 'Engine Size', 'null', 'multiSelectable', 'null', 'Engine Size', 'Dvigatel hajmi', 'Dvigatel hajmini tanlang', 'null', 'Dvigatel hajmi', 'null', 'Объем двигателя', 'Выберите объем двигателя', 'null', 'Объем двигателя', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('88799515-839f-48d5-805b-6745f61ba8a5', 'string', 'Select Fuel Type', 'null', 'oneSelectable', 'null', 'Fuel Type', 'null', 'multiSelectable', 'null', 'Fuel Type', 'Yoqilgʻi turi', 'Yoqilgʻi turini tanlang', 'null', 'Yoqilgʻi turi', 'null', 'Тип топлива', 'Выберите тип топлива', 'null', 'Тип топлива', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('49995b05-c3d5-41b4-ab4c-cec954453b84', 'string', 'Select Length', 'null', 'oneSelectable', 'null', 'Length', 'null', 'multiSelectable', 'null', 'Length of Watercraft', 'Suv transportining uzunligi', 'Suv transportining uzunligini tanlang', 'null', 'Transport uzunligi', 'null', 'Длина водного транспорта', 'Выберите длину транспорта', 'null', 'Длина транспорта', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('9c89063b-1c9b-4388-8c14-bc7a5e4808ba', 'string', 'Select Capacity', 'null', 'oneSelectable', 'null', 'Capacity', 'null', 'multiSelectable', 'null', 'Passenger Capacity', 'Yo‘lovchilar sig‘imi', 'Yo‘lovchilar sig‘imini tanlang', 'null', 'Yo‘lovchilar Sig‘imi', 'null', 'Пассажировместимость', 'Выберите пассажировместимость', 'null', 'Вместимость', 'null');
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('6c329c2a-d11a-4e9d-be58-3398c98cc00c', 'string', 'Write Down Description Text', 'null', 'textField', 'null', 'null', 'null', 'null', 'null', 'Description Text', 'Tavsif matni', 'Tavsif matnini yozing', 'null', 'null', 'null', 'Текст описания', 'Напишите текст описания', 'null', 'null', 'null');





--
-- Brand
-- Model
-- Year
-- Transmission Type
-- Fuel Type
-- Maximum Speed
-- Weight
-- Seating Capacity
-- Lights & Sirens
-- Sleeping Capacity





















