--Handbags and Wallets attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('20bd13e0-aa75-45e8-ba89-c4a906662084', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Eyewear attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('75ef8d0d-82fc-4ef3-bb24-9afa2e60eac4', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Watches attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('3546a25b-73da-47d8-83c0-19ab7997ec7b', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Fine Jewelry attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('be7737a1-df40-4429-8c9d-13d8701bf1db', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Scarves and Shawls attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('37f85bf4-92b9-4e5b-98ab-62aa51881268', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Hats and Caps attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('2fb7e41d-1705-40c0-81ca-b51cc0a5fe9a', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Gloves and Belts attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('a77d6a9a-f5a7-4743-8b3e-d8a3e0487347', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Home Accessories attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('62b828c8-bcb2-426d-aafc-7d89f12a1ae0', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Business Accessories attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('c0cd4984-af87-4e2f-93f3-a87e80e7d6b5', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Special Occasion Accessories attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('99c23474-ba7a-4815-b062-bc05c8d35cc2', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Luggage and Travel attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('892eb9c0-37b5-4984-8c67-c7f5ea4877d0', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

