--"Dogs"
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('9aea0433-7a18-458c-b09b-5d5e0fdedf68', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--"Cats"
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('d64d365f-98f3-414d-b445-a86a43784d1e', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--"Birds"
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('a51ee319-debe-41ee-b812-b3aa33e32303', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--"Horses"
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('85fc0ce6-8060-4570-88bb-a6c726aa2fec', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--"Reptiles"
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('886f6276-6213-4faf-b251-ddd14872f414', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--"Farm Animals"
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('809ed874-dde8-4998-af29-8f6a238226cd', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--"Pet Accessories"
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('d39b9536-a6ab-4078-bbe0-1beed4946751', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');
