--Fresh Flowers attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('85c07b95-e2e2-4f78-a598-73be698de708', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Flower Bouquets attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('710a071e-a788-4529-8c3e-e1727c56ab04', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Artificial Flowers attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('9adf1059-8fd9-4851-9a93-2dfe295a6c44', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Flower Arrangements attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('3b34c28c-fe95-4f2a-ae1f-40ef7bd3e70b', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Gift Sets attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('5b734047-3b87-4089-bf16-ad651ebef889', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Indoor Plants attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('b1d56ac8-0130-46fa-8f95-e5577ad90fa7', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Outdoor Plants attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('fc98d8e8-a18c-43f3-9ade-0f82b0ef95f5', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Potted Plants attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('9bcdd793-edd4-436a-b3f5-3992043408e7', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Garden Plants attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('fa5d3ba5-f81d-4eba-bcd6-eb3e105a4171', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Plush Toys attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('de336309-3943-4fdd-b551-5d0430b39da0', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Toy Cars and Vehicles attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('b883ce65-b784-40db-b94b-e97c7b02686f', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Creative Toys attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('94a7bd16-dfa0-4a76-a3bc-f8db010c5d30', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Baby Toys attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('48e63d64-1b03-47c6-8c62-5fd70ead5530', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');

--Educational Toys attribute keys
INSERT INTO attribute_keys (attribute_id, data_type, helper_text, sub_helper_text, widget_type, sub_widget_type, filter_text, sub_filter_text, filter_widget_type, sub_filter_widget_type, name, name_uz, helper_text_uz, sub_helper_text_uz, filter_text_uz, sub_filter_text_uz, name_ru, helper_text_ru, sub_helper_text_ru, filter_text_ru, sub_filter_text_ru) VALUES ('3754d4cc-bff6-420b-95d0-23aa5b9cf776', 'string', 'Select Type', 'null', 'oneSelectable', 'null','Type', 'null', 'multiSelectable', 'null','Type', 'Tur', 'Turni tanlang', 'null', 'Tur', 'null','Тип', 'Выберите тип', 'null', 'Тип', 'null');
